---
namespace: brianaddicks
name: adx
version: 1.0.7
description: Ansible module to ingest data into Azure Data Explorer
readme: README.md
authors:
    - Brian Addicks @brianaddicks

repository: https://github.com/brianaddicks/ansible-adx
issues: https://github.com/brianaddicks/ansible-adx/issues
build_ignore:
    - galaxy.yml.j2
    - release.yml
    - .github
    - .ansiblelint.yml
    - .yamllint.yml
    - '*.tar.gz'
license:
    - GPL-3.0-or-later
tags:
    - adx
    - azure-data-explorer
    - cloud
    - database
...
